.TH "affichage.AffichageJavaFX.CouleurOption" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
affichage.AffichageJavaFX.CouleurOption
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCouleurOption\fP (\fBCouleur\fP \fBcouleur\fP)"
.br
.ti -1c
.RI "\fBCouleur\fP \fBgetCouleur\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBCouleur\fP \fBcouleur\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "affichage\&.AffichageJavaFX\&.CouleurOption\&.CouleurOption (\fBCouleur\fP couleur)"

.SH "Member Function Documentation"
.PP 
.SS "\fBCouleur\fP affichage\&.AffichageJavaFX\&.CouleurOption\&.getCouleur ()"

.SS "String affichage\&.AffichageJavaFX\&.CouleurOption\&.toString ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBCouleur\fP affichage\&.AffichageJavaFX\&.CouleurOption\&.couleur\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for La légende Kaizoku: poudre noire et rhum doré from the source code\&.
