.TH "AffichageTerminal" 3 "La l√©gende Kaizoku: poudre noire et rhum dor√©" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AffichageTerminal \- ImplÈmentation de l'interface IAffichage pour un affichage en terminal\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
ImplÈmentation de l'interface IAffichage pour un affichage en terminal\&. 

Cette classe offre une interface utilisateur simple en ligne de commande pour interagir avec le jeu, y compris l'affichage du plateau, des messages aux joueurs, et la prise de dÈcisions\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for La l√©gende Kaizoku: poudre noire et rhum dor√© from the source code\&.
