.TH "src/tests Directory Reference" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tests Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAffichageJavaFXTest\&.java\fP"
.br
.ti -1c
.RI "file \fBJeuTest\&.java\fP"
.br
.ti -1c
.RI "file \fBTestDeplacements\&.java\fP"
.br
.ti -1c
.RI "file \fBTestPlateau\&.java\fP"
.br
.ti -1c
.RI "file \fBTestStart\&.java\fP"
.br
.ti -1c
.RI "file \fBTestStartJavaFX\&.java\fP"
.br
.in -1c
