.TH "src/affichage Directory Reference" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/affichage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAffichageJavaFX\&.java\fP"
.br
.ti -1c
.RI "file \fBAffichageTerminal\&.java\fP"
.br
.ti -1c
.RI "file \fBIAffichage\&.java\fP"
.br
.in -1c
