.TH "src/affichage/IAffichage.java" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/affichage/IAffichage.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBaffichage\&.IAffichage\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBaffichage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for La légende Kaizoku: poudre noire et rhum doré from the source code\&.
