.TH "md__r_e_a_d_m_e" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Les Pirates 
.PP
 
.SH "Description"
.PP
'Les Pirates' est un jeu de plateau interactif développé en Java avec JavaFX\&. Le jeu invite les joueurs à incarner des pirates naviguant à travers des mers dangereuses à la recherche d'un trésor caché\&. Chaque joueur doit surmonter des obstacles (cases rhum), ramasser des armes (case arme), combattre des adversaires (duels) et atteindre le trésor à la derniere case (case win)\&.
.SH "Fonctionnalités"
.PP
.IP "\(bu" 2
\fB\fBJeu\fP Multijoueur\fP : Supporte 2 à 10 joueurs, chacun choisissant un pirate unique et une couleur distinctive\&.
.IP "\(bu" 2
\fB\fBPlateau\fP Dynamique\fP : Le plateau de jeu comporte 30 cases, chacune offrant des défis ou des avantages spécifiques (rhums , armes, trésor)\&.
.IP "\(bu" 2
\fBCombats de Pirates\fP : Les joueurs peuvent s'affronter en duel lorsqu'ils se retrouvent sur des cases proches\&.
.IP "\(bu" 2
\fBSélection de Personnages\fP : Les joueurs choisissent parmi une variété de pirates\&.
.IP "\(bu" 2
\fBArmes à récupérer\fP : Les pirates peuvent trouver des armes tels que le pistolet, le mousquet , le sabre ou seulement leurs poings si ils n'ont pas de chance\&.
.IP "\(bu" 2
\fBBETA : Interface Graphique\fP : Une interface utilisateur riche et intuitive grâce à JavaFX, facilitant l'interaction et l'immersion dans le jeu\&.
.PP
.SH "Prérequis"
.PP
.IP "\(bu" 2
Java 11 ou version supérieure\&.
.IP "\(bu" 2
JavaFX SDK 11 ou version supérieure\&.
.PP
.SH "Installation"
.PP
.IP "1." 4
Clonez ce dépôt sur votre machine locale en utilisant \fRgit clone https://github.com/Bebel19/Les_Pirates.git\fP\&.
.IP "2." 4
Assurez-vous que JavaFX est correctement configuré dans votre environnement de développement\&.
.IP "3." 4
Lancez l'application via votre IDE ou en ligne de commande :
.PP
.PP
.PP
.nf
javac \-\-module\-path /chemin/vers/javafx\-sdk\-11/lib \-\-add\-modules javafx\&.controls,javafx\&.fxml \-d bin src/**/*\&.java
.fi
.PP
.PP
.PP
.nf
## Pour la version terminal dans la branche main

java \-\-module\-path /chemin/vers/javafx\-sdk\-11/lib \-\-add\-modules javafx\&.controls,javafx\&.fxml \-cp bin tests\&.TestStart
.fi
.PP
.PP
.PP
.nf
## Pour la version javaFX (beta) dans la branche Les_Pirates_JavaFX

java \-\-module\-path /chemin/vers/javafx\-sdk\-11/lib \-\-add\-modules javafx\&.controls,javafx\&.fxml \-cp bin tests\&.MonJeu
.fi
.PP
 
