.TH "Pirate" 3 "La l√©gende Kaizoku: poudre noire et rhum dor√©" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pirate \- ReprÈsente un pirate participant au jeu\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
ReprÈsente un pirate participant au jeu\&. 

Cette classe contient toutes les informations nÈcessaires sur un pirate, y compris ses points de vie, son nom, sa couleur, sa position sur le plateau, et son arme actuelle\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for La l√©gende Kaizoku: poudre noire et rhum dor√© from the source code\&.
