.TH "tests" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAffichageJavaFXTest\fP"
.br
.ti -1c
.RI "class \fBJeuTest\fP"
.br
.ti -1c
.RI "class \fBTestDeplacements\fP"
.br
.ti -1c
.RI "class \fBTestPlateau\fP"
.br
.ti -1c
.RI "class \fBTestStart\fP"
.br
.ti -1c
.RI "class \fBTestStartJavaFX\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for La légende Kaizoku: poudre noire et rhum doré from the source code\&.
