.TH "tests.JeuTest" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.JeuTest
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBtestDeplacerPirate\fP ()"
.br
.ti -1c
.RI "static void \fBtestEngagerDuel\fP ()"
.br
.ti -1c
.RI "static void \fBtestDeplacerPirateVersCaseNormale\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void tests\&.JeuTest\&.main (String[] args)\fR [static]\fP"

.SS "static void tests\&.JeuTest\&.testDeplacerPirate ()\fR [static]\fP"

.SS "static void tests\&.JeuTest\&.testDeplacerPirateVersCaseNormale ()\fR [static]\fP"

.SS "static void tests\&.JeuTest\&.testEngagerDuel ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for La légende Kaizoku: poudre noire et rhum doré from the source code\&.
