.TH "utils.PirateNom" 3 "La légende Kaizoku: poudre noire et rhum doré" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.PirateNom
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLUFFY\fP"
.br
.ti -1c
.RI "\fBFRANKY\fP"
.br
.ti -1c
.RI "\fBUSOPP\fP"
.br
.ti -1c
.RI "\fBNAMI\fP"
.br
.ti -1c
.RI "\fBCHOPPER\fP"
.br
.ti -1c
.RI "\fBSANJI\fP"
.br
.ti -1c
.RI "\fBJIMBEI\fP"
.br
.ti -1c
.RI "\fBZORO\fP"
.br
.ti -1c
.RI "\fBROBIN\fP"
.br
.ti -1c
.RI "\fBBROOK\fP"
.br
.ti -1c
.RI "\fBVIVI\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "utils\&.PirateNom\&.BROOK"

.SS "utils\&.PirateNom\&.CHOPPER"

.SS "utils\&.PirateNom\&.FRANKY"

.SS "utils\&.PirateNom\&.JIMBEI"

.SS "utils\&.PirateNom\&.LUFFY"

.SS "utils\&.PirateNom\&.NAMI"

.SS "utils\&.PirateNom\&.ROBIN"

.SS "utils\&.PirateNom\&.SANJI"

.SS "utils\&.PirateNom\&.USOPP"

.SS "utils\&.PirateNom\&.VIVI"

.SS "utils\&.PirateNom\&.ZORO"


.SH "Author"
.PP 
Generated automatically by Doxygen for La légende Kaizoku: poudre noire et rhum doré from the source code\&.
